# Bolean TRUE & FALSE 
# AND(Dan) --> & --> HANYA TRUE JIKA DUA DUANYA TRUE
# OR(ATAU)--> | --> TRUE JIKA SALAH SATUNYA TRUE, SELAIN ITU FALSE
# NOT(TIDAK/NEGASI) --> !
DF[DF$Sepal.Width> 3.1,]
DF[DF$Sepal.Width== 3.1,]
# SHINJI AUELLIO